"""
Valkyrie — AI Executive & Technical Report Generator
Aggregates scan artifacts, agent session logs, and AI analyses
into structured Markdown reports with CVSS scoring and remediation.
Named after the Valkyries who carry the worthy from the battlefield.
"""
import json
import time
import os
from datetime import datetime
import re
_CVSS_MAP = {
    "critical": {"score": "9.0-10.0", "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H"},
    "high":     {"score": "7.0-8.9",  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"},
    "medium":   {"score": "4.0-6.9",  "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:L"},
    "low":      {"score": "0.1-3.9",  "vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N"},
    "info":     {"score": "0.0",      "vector": "N/A - Informational"},
}
_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
def _cvss_row(severity):
    """Get CVSS score and vector for a severity level."""
    entry = _CVSS_MAP.get(severity.lower(), _CVSS_MAP["info"])
    return entry["score"], entry["vector"]
def _severity_sort_key(finding):
    """Sort findings by severity priority."""
    sev = finding.get("severity", "info").lower()
    try:
        return _SEVERITY_ORDER.index(sev)
    except ValueError:
        return 99
def generate_report(scan_data):
    """
    Generate a full Markdown security assessment report.
    Args:
        scan_data: dict with:
            - target: str
            - tool_outputs: list of {tool, output, analysis (optional)}
            - agent_summary: str (optional, from ReAct agent)
            - ai_analyses: list of analysis dicts from Heimdall (optional)
    Returns:
        str — complete Markdown report
    """
    target = scan_data.get("target", "Unknown Target")
    tool_outputs = scan_data.get("tool_outputs", [])
    agent_summary = scan_data.get("agent_summary", "")
    ai_analyses = scan_data.get("ai_analyses", [])
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = []
    _h = report.append  # shorthand
    _h(f"# 🛡️ YGGDRASIL SECURITY FRAMEWORK")
    _h(f"## Security Assessment Report")
    _h(f"")
    _h(f"| | |")
    _h(f"|---|---|")
    _h(f"| **Target** | `{target}` |")
    _h(f"| **Report Date** | {now} |")
    _h(f"| **Generated By** | ⚡ Valkyrie AI Report Engine |")
    _h(f"| **Framework** | Yggdrasil Security Framework v2.0.0 |")
    _h(f"")
    _h(f"---")
    _h(f"## 📋 Executive Summary")
    _h(f"")
    all_findings = []
    for analysis in ai_analyses:
        findings = analysis.get("findings", [])
        all_findings.extend(findings)
    total_findings = len(all_findings)
    critical_count = sum(1 for f in all_findings if f.get("severity", "").lower() == "critical")
    high_count = sum(1 for f in all_findings if f.get("severity", "").lower() == "high")
    if agent_summary:
        _h(f"_{agent_summary}_")
        _h(f"")
    _h(f"This automated security assessment was conducted against **{target}** ")
    _h(f"using the Yggdrasil Security Framework's multi-tool pipeline. ")
    _h(f"")
    if total_findings > 0:
        _h(f"- **{total_findings}** findings identified")
        _h(f"- **{critical_count}** critical, **{high_count}** high severity")
    else:
        _h(f"- Automated reconnaissance and vulnerability scanning completed.")
        _h(f"- Review detailed findings below for manual triage.")
    _h(f"")
    _h(f"---")
    _h(f"## 📊 Scan Statistics")
    _h(f"")
    tools_used = [t.get("tool", "unknown") for t in tool_outputs]
    _h(f"| Metric | Value |")
    _h(f"|---|---|")
    _h(f"| Tools Executed | {len(tool_outputs)} |")
    _h(f"| Tools Used | {', '.join(sorted(set(tools_used)))} |")
    _h(f"| Total Findings | {total_findings} |")
    _h(f"| Scan Duration | Automated pipeline |")
    _h(f"")
    if all_findings:
        _h(f"---")
        _h(f"## 🔍 Detailed Findings")
        _h(f"")
        all_findings.sort(key=_severity_sort_key)
        current_sev = None
        for f in all_findings:
            sev = f.get("severity", "info").lower()
            if sev != current_sev:
                current_sev = sev
                emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}.get(sev, "⚪")
                _h(f"### {emoji} {sev.upper()} Severity")
                _h(f"")
            score, vector = _cvss_row(sev)
            _h(f"**{f.get('type', 'Finding').upper()}:** {f.get('detail', 'No detail')}")
            _h(f"")
            _h(f"- **Type:** {f.get('type', 'N/A')}")
            _h(f"- **CVSS Score:** {score}")
            _h(f"- **CVSS Vector:** `{vector}`")
            _h(f"")
    if ai_analyses:
        _h(f"---")
        _h(f"## 🧠 AI Analysis Summaries")
        _h(f"")
        for i, analysis in enumerate(ai_analyses):
            summary = analysis.get("summary", "")
            model = analysis.get("model", "AI")
            if summary:
                _h(f"### Analysis #{i+1} (Model: {model})")
                _h(f"> {summary}")
                _h(f"")
    all_recs = []
    for analysis in ai_analyses:
        recs = analysis.get("recommendations", [])
        all_recs.extend(recs)
    if all_recs or tool_outputs:
        _h(f"---")
        _h(f"## ⚡ Recommendations & Next Steps")
        _h(f"")
        if all_recs:
            _h(f"### AI-Recommended Actions")
            _h(f"")
            for i, rec in enumerate(all_recs[:15]):
                _h(f"{i+1}. **{rec.get('action', 'Investigate')}**")
                if rec.get("tool"):
                    _h(f"   - Recommended tool: `{rec['tool']}`")
                if rec.get("reason"):
                    _h(f"   - Reason: {rec['reason']}")
                _h(f"")
        _h(f"### General Recommendations")
        _h(f"")
        _h(f"1. **Patch Management:** Apply all pending security patches to discovered services.")
        _h(f"2. **Access Control:** Review and restrict network access to critical services (SSH, RDP, SMB).")
        _h(f"3. **Web Hardening:** Configure WAF rules and disable directory listing on web servers.")
        _h(f"4. **Credential Audit:** Rotate any credentials or hashes that were discovered during testing.")
        _h(f"5. **Re-Scan:** After applying fixes, run a follow-up scan to verify remediation.")
        _h(f"")
    if tool_outputs:
        _h(f"---")
        _h(f"## 🛠️ Tool Execution Log")
        _h(f"")
        for i, entry in enumerate(tool_outputs):
            tool = entry.get("tool", "unknown")
            _h(f"### {i+1}. {tool}")
            _h(f"")
            output = entry.get("output", "")
            if output:
                preview = output[:500].strip()
                _h(f"```")
                _h(f"{preview}")
                if len(output) > 500:
                    _h(f"... (output truncated, {len(output)} total chars)")
                _h(f"```")
                _h(f"")
    _h(f"---")
    _h(f"")
    _h(f"*Report generated by **⚡ Valkyrie AI** — Yggdrasil Security Framework*")
    _h(f"*Confidential — For authorized security assessment purposes only.*")
    _h(f"*Generated: {now}*")
    return "\n".join(report)
def generate_report_from_agent(agent_session):
    """
    Generate a report from a completed ReAct agent session.
    Args:
        agent_session: dict from get_agent_status() result
    """
    steps = agent_session.get("steps", [])
    target = agent_session.get("target", "Unknown")
    tool_outputs = []
    for step in steps:
        if step.get("status") == "completed":
            tool_outputs.append({
                "tool": step.get("tool", "unknown"),
                "output": step.get("output", step.get("summary", "")),
                "summary": step.get("summary", ""),
                "reasoning": step.get("reasoning", "")
            })
    return generate_report({
        "target": target,
        "tool_outputs": tool_outputs,
        "agent_summary": agent_session.get("final_summary", ""),
        "ai_analyses": []
    })
def generate_report_from_terminals(terminals):
    """
    Generate a report from frontend terminal window contents.
    Args:
        terminals: list of {tool, target, output, analysis (optional)}
    """
    if not terminals:
        return "# Error: No scan data provided.\n\nRun at least one tool scan before generating a report."
    target = terminals[0].get("target", "Unknown")
    tool_outputs = []
    ai_analyses = []
    for t in terminals:
        tool_outputs.append({
            "tool": t.get("tool", "unknown"),
            "output": t.get("output", ""),
        })
        if t.get("analysis"):
            ai_analyses.append(t["analysis"])
    return generate_report({
        "target": target,
        "tool_outputs": tool_outputs,
        "ai_analyses": ai_analyses,
        "agent_summary": ""
    })
def markdown_to_html(md_text):
    """
    Convert a Markdown report to a standalone HTML page suitable for print-to-PDF.
    Uses only built-in string processing — no external dependencies.
    """
    lines = md_text.split("\n")
    html_lines = []
    in_code_block = False
    in_table = False
    html_lines.append("<!DOCTYPE html>")
    html_lines.append('<html lang="en"><head><meta charset="UTF-8">')
    html_lines.append('<title>Yggdrasil Security Report</title>')
    html_lines.append('<style>')
    html_lines.append('body{font-family:Segoe UI,Arial,sans-serif;max-width:900px;margin:40px auto;padding:20px;color:#1a1a1a;line-height:1.7;background:#fff}')
    html_lines.append('h1{color:#2e3440;border-bottom:3px solid #bf616a;padding-bottom:10px}')
    html_lines.append('h2{color:#3b4252;border-bottom:2px solid #d08770;padding-bottom:8px;margin-top:30px}')
    html_lines.append('h3{color:#4c566a;margin-top:20px}')
    html_lines.append('code{background:#eceff4;padding:2px 6px;border-radius:3px;font-size:0.9em}')
    html_lines.append('pre{background:#2e3440;color:#d8dee9;padding:15px;border-radius:5px;overflow-x:auto;font-size:13px;line-height:1.4}')
    html_lines.append('table{border-collapse:collapse;width:100%;margin:15px 0}')
    html_lines.append('th,td{border:1px solid #d8dee9;padding:8px 12px;text-align:left}')
    html_lines.append('th{background:#eceff4;font-weight:bold}')
    html_lines.append('blockquote{border-left:4px solid #88c0d0;margin:15px 0;padding:10px 20px;background:#f8f9fa;font-style:italic}')
    html_lines.append('hr{border:none;border-top:2px solid #eceff4;margin:25px 0}')
    html_lines.append('@media print{body{margin:0;padding:15px}h2{page-break-before:always}h2:first-of-type{page-break-before:avoid}}')
    html_lines.append('</style></head><body>')
    for line in lines:
        if line.strip().startswith("```"):
            if in_code_block:
                html_lines.append("</pre>")
                in_code_block = False
            else:
                html_lines.append("<pre>")
                in_code_block = True
            continue
        if in_code_block:
            html_lines.append(line)
            continue
        if line.strip() == "---":
            html_lines.append("<hr>")
            continue
        if line.startswith("#### "):
            html_lines.append(f"<h4>{line[5:]}</h4>")
            continue
        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
            continue
        if line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
            continue
        if line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
            continue
        if "|" in line and line.strip().startswith("|"):
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if all(c.replace("-", "").replace(" ", "") == "" for c in cells):
                continue  # skip separator row
            tag = "th" if not in_table else "td"
            html_lines.append("<tr>" + "".join(f"<{tag}>{c}</{tag}>" for c in cells) + "</tr>")
            if not in_table:
                html_lines.insert(-1, "<table>")
                in_table = True
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False
        if line.startswith("> "):
            html_lines.append(f"<blockquote>{line[2:]}</blockquote>")
            continue
        line = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)
        line = re.sub(r'\*(.+?)\*', r'<em>\1</em>', line)
        line = re.sub(r'`(.+?)`', r'<code>\1</code>', line)
        if not line.strip():
            html_lines.append("<br>")
        else:
            html_lines.append(f"<p>{line}</p>")
    if in_code_block:
        html_lines.append("</pre>")
    if in_table:
        html_lines.append("</table>")
    html_lines.append("</body></html>")
    return "\n".join(html_lines)
